---
abstract: 'PIS type for Moose classes'
author:
  - 'Breno G. de Oliveira, C<< <garu at cpan.org> >>'
  - 'Breno G. de Oliveira <garu@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Types-PIS
no_index:
  directory:
    - inc
    - t
requires:
  Business::BR::PIS: 0
  MooseX::Types: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
